services:
  - type: web
    name: datlas-api
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    rootDir: backend
    envVars:
      - key: DEBUG
        value: "false"
